<table >
    <tr>
        <th>Id</th>
        <th>Titolo Blog</th>
        <th>Titolo post</th>
        <th>Id_Autore</th>
        <th>Modifica</th>
        <th>Cancella</th>
    </tr>
    <?php foreach($this->risultato as $post) :?>

        <?php $id=$post['id']; ?>
        <?php $id_user=$post['id_user'];?>
        <?php echo "<tr>
          <td>" . $post['id'] . "</td>
          <td>" . $post['titoloblog'] . "</td>
          <td>" . $post['titolo'] . "</td>
          <td>" . $post['id_user'] . "</td>
          <td>"; ?><a href="<?= $this->url(array(
            'controller'=>'staff',
            'action'=>'modificablog',
            'id'=>"$id",
            'id_user'=>"$id_user"),
            'default',true);
        ?>"><?php echo $this->bottonemod ?></a>
        <?php echo"</td>
        <td>"; ?><a href="<?= $this->url(array(
            'controller'=>'staff',
            'action'=>'cancellablog',
            'id'=>"$id",
            'id_user'=>"$id_user"),
            'default',true);
        ?>"><?php echo $this->bottonedel ?></a>
        <?php echo"</td>
        </tr>"; ?>

    <?php endforeach ?>
</table>