<div class="primary-content"><div class="datagrid">
    <table class="thead" border="2" cellpadding="3" bgcolor="white">
    <tr>
        <th>Titolo Blog</th>
        <th>Cancella</th>
    </tr>
    <?php foreach($this->risultato as $post) :?>


        <?php $id=$post['idblog']; ?>
        <?php $id_user=$post['id_user'];?>
        <?php echo "<tr>
          <td>" . $post['titolo'] . "</td>
          <td>"; ?><a href="<?= $this->url(array(
            'controller'=>'staff',
            'action'=>'cancellainteroblog',
            'id'=>"$id",
            'id_user'=>"$id_user"),
            'default',true);
        ?>"><?php echo $this->bottonedel ?></a>
        <?php echo"</td>
        </tr>"; ?>

    <?php endforeach ?>
</table>
</div></div>