<div class="panel">
    <div class="title">
        <h1>FAQ</h1>
    </div>
<div class="content padBottom">
<li>"Now that I know everything, my friend!  Ah! that's very good</li>
<p>Con PeoleBlog potrai: Fusce eleifend sapien nec felis volutpat convallis. Donec condimentum mollis laoreet. Suspendisse dignissim est sodales tortor pellentesque gravida.</p>

<li>  But go on, go on</li>
<p>Con PeoleBlog potrai: Fusce eleifend sapien nec felis volutpat convallis. Donec condimentum mollis laoreet. Suspendisse dignissim est sodales tortor pellentesque gravida.</p>

<li>  First, though, let me tell you that those gentlemen have put themselves to a useless expense</li>
<p>Con PeoleBlog potrai: Fusce eleifend sapien nec felis volutpat convallis. Donec condimentum mollis laoreet. Suspendisse dignissim est sodales tortor pellentesque gravida.</p>

<li>" "Useless!" said Fix</li>
<p>Con PeoleBlog potrai: Fusce eleifend sapien nec felis volutpat convallis. Donec condimentum mollis laoreet. Suspendisse dignissim est sodales tortor pellentesque gravida.</p>

<li>  "You speak confidently</li>
<p>Con PeoleBlog potrai: Fusce eleifend sapien nec felis volutpat convallis. Donec condimentum mollis laoreet. Suspendisse dignissim est sodales tortor pellentesque gravida.</p>

<li>  It's clear that you don't know how large the sum is</li>
<p>Con PeoleBlog potrai: Fusce eleifend sapien nec felis volutpat convallis. Donec condimentum mollis laoreet. Suspendisse dignissim est sodales tortor pellentesque gravida.</p>

<li>" "Of course I do," returned Passepartout</li>
<p>Con PeoleBlog potrai: Fusce eleifend sapien nec felis volutpat convallis. Donec condimentum mollis laoreet. Suspendisse dignissim est sodales tortor pellentesque gravida.</p>

<li>  "Twenty thousand pounds</li>
<p>Con PeoleBlog potrai: Fusce eleifend sapien nec felis volutpat convallis. Donec condimentum mollis laoreet. Suspendisse dignissim est sodales tortor pellentesque gravida.</p>

<li>"</li>

<li> "Fifty-five thousand!" answered Fix, pressing his companion's hand</li>
<p>Con PeoleBlog potrai: Fusce eleifend sapien nec felis volutpat convallis. Donec condimentum mollis laoreet. Suspendisse dignissim est sodales tortor pellentesque gravida.</p>

<li> "What!" cried the Frenchman</li>
<p>Con PeoleBlog potrai: Fusce eleifend sapien nec felis volutpat convallis. Donec condimentum mollis laoreet. Suspendisse dignissim est sodales tortor pellentesque gravida.</p>

<li>  "Has Monsieur Fogg dared&mdash;fifty-five thousand pounds!  Well, there's all the more reason for not losing an instant," he continued, getting up hastily</li>
<p>Con PeoleBlog potrai: Fusce eleifend sapien nec felis volutpat convallis. Donec condimentum mollis laoreet. Suspendisse dignissim est sodales tortor pellentesque gravida.</p>

<li> Fix pushed Passepartout back in his chair, and resumed: "Fifty-five thousand pounds; and if I succeed, I get two thousand pounds</li>
<p>Con PeoleBlog potrai: Fusce eleifend sapien nec felis volutpat convallis. Donec condimentum mollis laoreet. Suspendisse dignissim est sodales tortor pellentesque gravida.</p>

<li>  If you'll help me, I'll let you have five hundred of them</li>
<p>Con PeoleBlog potrai: Fusce eleifend sapien nec felis volutpat convallis. Donec condimentum mollis laoreet. Suspendisse dignissim est sodales tortor pellentesque gravida.</p>

<li>"</li>
<p>Con PeoleBlog potrai: Fusce eleifend sapien nec felis volutpat convallis. Donec condimentum mollis laoreet. Suspendisse dignissim est sodales tortor pellentesque gravida.</p>

<li> "Help you?" cried Passepartout, whose eyes were standing wide open</li>
<p>Con PeoleBlog potrai: Fusce eleifend sapien nec felis volutpat convallis. Donec condimentum mollis laoreet. Suspendisse dignissim est sodales tortor pellentesque gravida.</p>

<li> "Yes; help me keep Mr</li>
    </div>
</div>