<div class="panel">
    <div class="title">
        <h1>FAQ</h1>
    </div>
<div class="content padBottom">

    <br><br>
    <li>Cosa è PeopleBlog?</li>

    <p>PeopleBlog è una community che permette agli utenti di mantenersi in contatto con i loro amici e di parlare dei loro
interessi.</p>
    <li>Come mi iscrivo?</li>
    <p>Iscriversi a PeopleBlog è estremamente semplice! Dalla Homepage vi basterà cliccare su "Registrati" e compilare
    i dati necessari per creare un account.</p>

    <li>E se non voglio rivelare la mia età a nessuno?</li>
    <p>Non c'è problema, noi di PeopleBlog teniamo alla privacy dei nostri utenti. Potrete infatti scegliere se le vostre
    informazioni personali saranno visibili a tutti o solo al vostro gruppo di amici</p>

    <li>Perchè non riesco a creare un account?</li>
    <p>Non è possibile creare due account con la stessa e-mail. Assicuratevi di non aver già creato un account
    in precedenza.</p>

    

    </div>
</div>