<div class="panel">
    <div class="title">
        <h1>BEnvenuto, iscriviti a PeopleBlog</h1>
        <h2>Crea il tuo profilo e il tuo blog e aggiungi tanti amici </h2>
    </div>
    <div class="content padBottom"> <img src="images/executive.gif" />
        <p>Con PeoleBlog potrai: Fusce eleifend sapien nec felis volutpat convallis. Donec condimentum mollis laoreet. Suspendisse dignissim est sodales tortor pellentesque gravida.</p>
        <p>Fusce non justo a turpis vestibulum pulvinar. In hac habitasse platea dictumst. Nam ultricies facilisis diam, vitae venenatis risus imperdiet at. Pellentesque vel metus vitae risus sollicitudin molestie feugiat nec justo. </p>
        <p>Integer condimentum, ante et lacinia sagittis, diam velit bibendum nulla, nec euismod lorem metus eu justo. Nunc nec est dolor. Phasellus aliquam dapibus odio, eget pretium eros rutrum a. Maecenas at libero quam. </p>
        <p>Duis auctor iaculis congue. Vestibulum nec bibendum est. Integer sed accumsan nisl Phasellus aliquam dapibus odio, eget pretium eros rutrum</p>
    </div>
    <div class="button-link"><a href="#">| - Read More - |</a> </div>
    <div class="clearing"></div>
    <div class="title padTop">
        <h1 class="padTop">Cum sociis natoque penatibus</h1>
    </div>
    <div class="content">
        <p>Integer condimentum, ante et lacinia sagittis, diam velit bibendum nulla, nec euismod lorem metus eu justo. Nunc nec est dolor. Phasellus aliquam dapibus odio, eget pretium eros rutrum a. Maecenas at libero quam. </p>
    </div>
    <div class="button-link"><a href="#">| - Read More - |</a> </div>
</div>
