<div class="panel">
    <div class="title">
        <h1>Benvenuto, iscriviti a PeopleBlog</h1>
        <h2>Crea il tuo profilo e il tuo blog e aggiungi tanti amici </h2>
    </div>
    <div class="content padBottom"> <img src="images/executive.gif" />
        <p><h2>Con PeopleBlog potrai entrare a far parte della nostra comunità e mantenerti in contatto con i tuoi amici! Crea i tuoi blog
        sugli argomenti che più ti piacciono e condividi le tue passioni con chi vuoi, leggi ciò che scrivono i tuoi amici e di la tua
        opinione commentando i loro articoli!</h2></p>
    <div class="clearing"></div>
    <div class="title padTop">
        <h1 class="padTop">Per informazioni o segnalazioni: <a href="peopleblog@hotmail.com">Contattaci</a></h1>
    </div>
    <a href="http://tweb.dii.univpm.it/~grp_62/ZendProject/public/Documentazione.pdf">| - DOCUMENTAZIONE- |</a>
</div>
