<div class="panel">
    <div class="title">
        <h1>REGOLAMENTO</h1>
    </div>
    <div class="content padBottom">
        <li>Privacy:</li>
        <p>PeopleBlog non è responsabile dei dati inseriti dagli utenti. E' vietato: <br>
            ● Inserire informazioni false o volte a nascondere la propria identità. <br>
            ● Creare un account per conto di un'altra persona a sua insaputa. <br>
            ● Registrarsi con più di un account personale. <br>
            ● Usare strumenti automatizzati come bot di raccolta per ottenere informazioni riservate di un utente. <br>
            Ogni infrazione del precedente regolamento porterà alla cancellazione del proprio account e al ban permanente
            dalla comunità.
        </p>

        <li>Sicurezza:</li>
        <p>Lo staff di PeopleBlog si impegna al massimo affinchè il nostro sia un sito sicuro, ma non possiamo garantirlo.
            Abbiamo bisogno che gli utenti contribuiscano a tutelare la sicurezza di PeopleBlog, ovvero che si impegnino a:<br>
            ● Non pubblicare comunicazioni commerciali non autorizzate (ad esempio spam).<br>
            ● Non intraprendere azioni di marketing multi-livello illegali. <br>
            ● Non caricare virus o altri codici dannosi.<br>
            ● Non usare il sito per scopi illegali, ingannevoli, malevoli o discriminatori. <br>
           </p>

        <li>Comportamento:</li>
        <p>
            ● Ogni messaggio esprime esclusivamente il punto di vista del suo autore, non il punto di vista degli amministratori del forum.
            L'utente verrà ritenuto il solo responsabile delle violazioni eventualmente compiute tramite il presente servizio.<br>

            ● L'utente concorda inoltre di non inviare messaggi abusivi, diffamatori, minatori o qualunque altro materiale che possa violare le leggi in vigore.<br>

            ● L'utente concorda che lo staff del sito ha il diritto di rimuovere o modificare un post ogni volta che lo ritengano necessario.<br>

            ● Non sono consentiti insulti personali tra gli utenti o offese alle istituzioni o alla religione di qualunque fede.<br>

            ● Non sono consentiti commenti denigratori, offensivi, sarcastici e sbeffeggiatori, anche se non si è d'accordo con quanto detto da un utente.<br>

            ● Sono inoltre vietati: il razzismo ed ogni apologia dell'inferiorità o superiorità di una razza rispetto alle altre.<br>
            - atteggiamenti e/o posizioni di contestazione, presi a titolo gratuito, palesemente ostili nei confronti dei moderatori e degli amministratori del sito <br>
            - atteggiamenti e/o posizioni di contestazione, presi a titolo gratuito, palesemente ostili nei confronti degli altri utenti del sito <br>
            - incitamento al mancato rispetto delle presenti regole miranti alla esclusiva destabilizzazione della normale e pacifica partecipazione attiva alla community <br>

            La deliberata inosservanza di quanto riportato sopra comporterà l'immediato ban dal forum, a discrezione dei moderatori e/o degli amministratori d PeopleBlog.<br>

        </p>
    </div>
</div>