
<div class="sidebar marLeft30">
    <div class="panel">
        <div class="title">
            <h1><?php echo $this->nome; ?> <?php echo $this->cognome; ?></h1>
        </div>
        <div class="profilepic">
            <img src="public/images/img2.jpg" />
        </div>
        <div class="content">

            <?php echo $this->interessi; ?>


        </div>
        <div class="button-link"></div>
    </div>

</div>