<ul>
    <li><a href="<?= $this->url(array(
            'controller'=>'user',
            'action'=>'index',),
            'default',true);
        ?>"
           title="Home">Home</a>
    </li>
    <li><a href="<?= $this->url(array(
            'controller'=>'user',
            'action'=>'showuserprofile',
            'id'=>$nome=Zend_Auth::getInstance()->getIdentity()->id),
            'default',true);
        ?>"
           title="Profilo"><?php $nome=Zend_Auth::getInstance()->getIdentity()->Nome;
            $cognome=Zend_Auth::getInstance()->getIdentity()->Cognome;
            echo $nome.' '.$cognome.' '; ?></a>
    </li>
    <li><a href="<?= $this->url(array(
            'controller'=>'user',
            'action'=>'modificaprofilo',),
            'default',true);
        ?>"
           title="Modifica profilo">Modifica Profilo</a>
    </li>
    <?php $user=Zend_Auth::getInstance(); ?>
    <?php if($user->hasIdentity()) :?>
        <li><a href="<?= $this->url(array(
                'controller'=>'user',
                'action'=>'logout'),
                'default',true);
            ?>"
               title="Disconnettiti"><i class="icon-user"></i>Logout</a></li>
    <?php endif ?>

    <?php if($user->hasIdentity()) :?>
        <?php $permesso=$user->getIdentity()->ruolo; ?>
        <?php if((!$permesso==null)&&($permesso=='admin')) :?>

            <li><a href="<?= $this->url(array(
                    'controller'=>'admin',
                    'action'=>'index'),
                    'default',true);
                ?>"
                   title="Gestisci sito"><i class="icon-user"></i>Amministrazione</a></li>
        <?php endif ?>

    <?php endif ?>

</ul>