<ul>
    <li><a href="<?= $this->url(array(
            'controller'=>'public',
            'action'=>'index',),
            'default',true);
        ?>"
           title="Home">Home</a>
    </li>
    <li><a href="<?= $this->url(array(
            'controller'=>'user',
            'action'=>'modificaprofilo',),
            'default',true);
        ?>"
           title="Modifica profilo">Modifica Profilo</a>
    </li>
    <li><a href="<?= $this->url(array(
            'controller'=>'user',
            'action'=>'cambiaimmagine',),
            'default',true);
        ?>"
           title="Cambia immagine">Cambia Immagine</a>
    </li>
    <?php $user=Zend_Auth::getInstance(); ?>
    <?php if($user->hasIdentity()) :?>
        <li><a href="<?= $this->url(array(
                'controller'=>'user',
                'action'=>'logout'),
                'default',true);
            ?>"
               title="Disconnettiti"><i class="icon-user"></i>Logout</a></li>
    <?php endif ?>
    <?php $blog=$user->getIdentity()->blog; ?>
    <?php if($blog==0) :?>
    <li><a href="<?= $this->url(array(
            'controller'=>'user',
            'action'=>'creablog',),
            'default',true);
        ?>"
           title="Crea blog">Crea blog</a>
    </li>
    <?php endif; ?>
    <?php if($blog==1) :?>
    <li><a href="<?= $this->url(array(
            'controller'=>'blog',
            'action'=>'index',),
            'default',true);
        ?>"
           title="Gestisci">Gestisci blog</a>
    </li>
    <?php endif; ?>
    <li><a href="<?= $this->url(array(
            'controller'=>'user',
            'action'=>'show',
            'a'=>$user->getIdentity()->Nome,
            'b'=>$user->getIdentity()->Cognome,
            'c'=>$user->getIdentity()->eta,
            'd'=>$user->getIdentity()->interessi,
            'e'=>$user->getIdentity()->immagine),
            'default',true);
        ?>"
           title="Profilo">Profilo pubb</a>
    </li>

</ul>