<ul>
    <li><a href="<?= $this->url(array(
            'controller'=>'public',
            'action'=>'index',),
            'default',true);
        ?>"
           title="Home">Home</a>
    </li>

    <?php $user=Zend_Auth::getInstance(); ?>
        <?php if($user->hasIdentity()) :?>
            <li><a href="<?= $this->url(array(
                    'controller'=>'user',
                    'action'=>'logout'),
                    'default',true);
                ?>"
                   title="Disconnettiti"><i class="icon-user"></i>Logout</a></li>
        <?php endif ?>
    <li><a href="<?= $this->url(array(
					'controller'=>'admin',
					'action'=>'aggiungiutente',),
					'default',true);
					?>"
			title="Aggiunge un nuovo utente">Aggiungi Utente</a>
	</li>
	<li><a href="<?= $this->url(array(
					'controller'=>'admin',
					'action'=>'seleziona',),
					'default',true);
					?>"
			title="Modifica o cancella informazioni utente esistente">Modifica/Cancella Utente</a>
	</li>
</ul>