<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('ProgTweb');
echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    //mettere sul bootstrap e togliere dai singoli layout e mettere this->headscript
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/style.css'); ?>
    <?php echo $this->headLink()->prependStylesheet('http://fonts.googleapis.com/css?family=Droid+Sans:400,700'); ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/js/jquery-ui.min.css'); ?>
    <script src="<?php echo $this->baseUrl("js/jquery.js")?>"></script>
    <script src="<?php echo $this->baseUrl("js/jquery-ui.min.js")?>"></script>
    <!--<script src="<?php echo $this->baseUrl("js/searchbox.js")?>"></script> -->


    <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>
<div class="header-wrap">
    <div class="header">
        <div class="menu">
            <?= $this->render('_navuser.phtml')?>
        </div>
        <div class="social-media">
            <ul>
                <li><a href="#"><img src="<?=$this->baseUrl('images/aim.gif')?>" /></a></li>
                <li><a href="#"><img src="<?=$this->baseUrl('images/facebook.gif')?>" /></a></li>
                <li><a href="#"><img src="<?=$this->baseUrl('images/linkedin.gif')?>" /></a></li>
                <li><a href="#"><img src="<?=$this->baseUrl('images/twitter.gif')?>" /></a></li>
            </ul>
        </div>
    </div>
</div>
<!-- end of header wrapper -->
<div class="logo-sarch-wrap">
    <div class="logo-search-container">
        <div class="logo">
            <h1>PeopleBlog</h1>
        </div>

            <div class="search-input">
                <input id="searchbox" type="text" placeholder="Cerca Utenti..." />
            </div>

        </div>
    </div>
</div>
<!-- end of header wrapper -->
<?php /*<div class="banner-wrap marginBottom">
    <div class="banner-left"><img src="images/left-shadow.gif" /></div>
    <div class="banner">
        <div class="banner-image">
            <div class="banner-data">
                <div class="caption1">
                    <h1>Pellentesque et aliquet massa donec</h1>
                </div>
                <div class="caption2">
                    <h2> sit amet auctor anteroin sit amet elit doco ipory</h2>
                </div>
                <div class="caption3"> Fusce vel ipsum magna, nec tempor neque<br />
                    orem ipsum dolor sit ametris odonil kusi </div>
            </div>
        </div>
    </div>
    <div class="banner-right"><img src="images/right-shadow.gif" /></div>
</div>*/ ?>
<!-- end of header wrapper -->
<!-- end of panel wrapper -->
<div class="page-wrapper">
    <?php echo $this->layout()->content; ?>
    
    <!-- end of Sidebar -->
</div>
<!-- end of page wrapper -->
<div class="clearing"></div>
<div class="footer-wrapper marginTop">
    <div class="footer"> Copyright (c) websitename. All rights reserved. Designed by: <a href="http://alltemplateneeds.com">www.alltemplateneeds.com</a> Images From: www.photorack.net </div>
</div>

<script>
$(document).ready(function () {




$("#searchbox").autocomplete({
source: function( request, response ){
    if(request.term.endsWith("*")){
    request.substring(0, str.length - 1);}
    
        $.ajax({
            type: 'POST',
            url: '<?php echo $this->url(array('controller' => 'user', 'action' => 'updateajax'));?>',
            dataType: "json",
            data: {

                q: request.term
            },
            success: function (data) {
                console.log(typeof data);
                console.log(data);
// Handle 'no match' indicated by [ "" ] response
                response(data.length === 1 && data[0].length === 0 ? [] : data);
            }
        });



},
minLength: 2,
focus: function (event, ui) {
$("#searchbox").val(ui.item.Nome + " " + ui.item.Cognome)
return false;
},
select: function (event, ui) {

var url = "<?php echo $this->url(array('controller' => 'user','action' =>'showuserprofile','id'=>''));?>"+ui.item.id ;
location.href = url;
return false;
},
}).autocomplete("instance")._renderItem = function (ul, item) {
var $li = $("<li>");
    $li.addClass("searchItem");

    $outerDiv = $("<div>");
        $outerDiv.appendTo($li);

        $imageDiv = $("<div>");
            $imageDiv.addClass("contactImageDiv");
            $imageDiv.appendTo($outerDiv);

            $img = $("<img>");
            $img.addClass("contactImage");
            $img.attr("src", item.imgUrl);
            $img.appendTo($imageDiv);

            $name = $("<div>");
                $name.addClass("nameDiv");
                $name.append(item.Nome + " " + item.Cognome + "<br/><span style='font-style:italic'>"+"</span>");
                $name.appendTo($outerDiv);

                $li.appendTo(ul);

                return $li;
                };

                })


</script>

</body>
</html>