<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('ProgTweb');
echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    //mettere sul bootstrap e togliere dai singoli layout e mettere this->headscript
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/style.css'); ?>
    <?php echo $this->headLink()->prependStylesheet('http://fonts.googleapis.com/css?family=Droid+Sans:400,700'); ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/js/jquery-ui.min.css'); ?>
    <script src="<?php echo $this->baseUrl("js/jquery.js")?>"></script>
    <script src="<?php echo $this->baseUrl("js/jquery-ui.min.js")?>"></script>
    <!--<script src="<?php echo $this->baseUrl("js/searchbox.js")?>"></script> -->


    <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>
<div class="header-wrap">
    <div class="header">
        <div class="menu">
            <?= $this->render('_navuser.phtml')?>
        </div>
        <div class="social-media">
            <ul>
                <li><a href="#"><img src="<?=$this->baseUrl('images/aim.gif')?>" /></a></li>
                <li><a href="#"><img src="<?=$this->baseUrl('images/facebook.gif')?>" /></a></li>
                <li><a href="#"><img src="<?=$this->baseUrl('images/linkedin.gif')?>" /></a></li>
                <li><a href="#"><img src="<?=$this->baseUrl('images/twitter.gif')?>" /></a></li>
            </ul>
        </div>
    </div>
</div>
<!-- end of header wrapper -->
<div class="logo-sarch-wrap">
    <div class="logo-search-container">
        <div class="logo">
            <h1>PeopleBlog</h1>
        </div>

            <div class="search-input">
                <input id="searchbox" type="text" placeholder="Cerca Utenti..." />
            </div>

        </div>
    </div>
</div>
<!-- end of header wrapper -->
<?php /*<div class="banner-wrap marginBottom">
    <div class="banner-left"><img src="images/left-shadow.gif" /></div>
    <div class="banner">
        <div class="banner-image">
            <div class="banner-data">
                <div class="caption1">
                    <h1>Pellentesque et aliquet massa donec</h1>
                </div>
                <div class="caption2">
                    <h2> sit amet auctor anteroin sit amet elit doco ipory</h2>
                </div>
                <div class="caption3"> Fusce vel ipsum magna, nec tempor neque<br />
                    orem ipsum dolor sit ametris odonil kusi </div>
            </div>
        </div>
    </div>
    <div class="banner-right"><img src="images/right-shadow.gif" /></div>
</div>*/ ?>
<!-- end of header wrapper -->
<!-- end of panel wrapper -->
<div class="page-wrapper">
    <?php echo $this->layout()->content; ?>
    
    <!-- end of Sidebar -->
</div>
<!-- end of page wrapper -->
<div class="clearing"></div>
<div class="footer-wrapper marginTop">
    <div class="footer"> Copyright (c) websitename. All rights reserved. Designed by: <a href="http://alltemplateneeds.com">www.alltemplateneeds.com</a> Images From: www.photorack.net </div>
</div>

<script>
$(document).ready(function () {




$("#searchbox").autocomplete({
source: function( request, response ) {
$.ajax( {
    type: 'POST',
url: '<?php echo $this->url(array('controller' => 'user','action' => 'updateajax'));?>',
dataType: "json",
data: {
q: request.term
},
success: function( data ) {
console.log(typeof data);
    console.log(data);
// Handle 'no match' indicated by [ "" ] response
response( data.length === 1 && data[ 0 ].length === 0 ? [] : data );
}
} );
},
minLength: 2,
focus: function (event, ui) {
$("#searchbox").val(ui.item.Nome + " " + ui.item.Cognome)
return false;
},
select: function (event, ui) {
    //il mio problema è qui, la prima ricerca funziona la seconda ricerca no, cioè quendo esegui la ricerca per la seconda volta nell'url del browser il parametro
    // id si duplica
    // visto che da quello che mi dici e comunque dalla teoria il php viene caricato subito
    //c'è un metodo specifico per generare quell'url nel modo in cui serve a me o devo
    //creare io una funzione che mi modifichi la stringa che genera il php per renderla come voglio?ricer


var url = "<?php echo $this->url(array('controller' => 'user','action' =>'showuserprofile','id'=>'<script>ui.item.id</script>'));?>"+"/id/"+ui.item.id ;
location.href = url;
return false;
},
}).autocomplete("instance")._renderItem = function (ul, item) {
var $li = $("<li>");
    $li.addClass("searchItem");

    $outerDiv = $("<div>");
        $outerDiv.appendTo($li);

        $imageDiv = $("<div>");
            $imageDiv.addClass("contactImageDiv");
            $imageDiv.appendTo($outerDiv);

            $img = $("<img>");
            $img.addClass("contactImage");
            $img.attr("src", item.imgUrl);
            $img.appendTo($imageDiv);

            $name = $("<div>");
                $name.addClass("nameDiv");
                $name.append(item.Nome + " " + item.Cognome + "<br/><span style='font-style:italic'>"+"</span>");
                $name.appendTo($outerDiv);

                $li.appendTo(ul);

                return $li;
                };

                })


</script>

</body>
</html>

<!--*
var contacts = [
{
"firstName": "Petrer",
"lastName": "Parkscsdcer",
"heroName": "Spidermansd",
"imgUrl": "img/spiderman.png"
},
{
"firstName": "Brurce",
"lastName": "Bannecasdcr",
"heroName": "Hucwrcwlk",
"imgUrl": "img/hulk.png"
}, {
"firstName": "Torny",
"lastName": "Starsdccsdk",
"heroName": "Ironmsdcdcsaan",
"imgUrl": "img/ironman.png"
}, {
"firstName": "Bscsacrucre",
"lastName": "Wayrrevne",
"heroName": "Batmvrwvean",
"imgUrl": "img/batman.png"
},
{
"firstName": "Peterevrr",
"lastName": "Parkvreer",
"heroName": "Spidervereavman",
"imgUrl": "img/spiderman.png"
},
{
"firstName": "Brucrrvrevrre",
"lastName": "Banvearvervner",
"heroName": "Hubrrblk",
"imgUrl": "img/hulk.png"
}, {
"firstName": "To34fefnyr",
"lastName": "Staverk",
"heroName": "Ironmververan",
"imgUrl": "img/ironman.png"
}, {
"firstName": "Brverucerrrrr",
"lastName": "Wayvervreververne",
"heroName": "Batmrrrrvevan",
"imgUrl": "img/batman.png"
},{
"firstName": "Perrter",
"lastName": "Parkvervreveber",
"heroName": "Spiderbrbytrbebrman",
"imgUrl": "img/spiderman.png"
},
{
"firstName": "Brrrrrrruce",
"lastName": "Bannrberbernjer",
"heroName": "Hubrbrynjrylk",
"imgUrl": "img/hulk.png"
}, {
"firstName": "Tronry",
"lastName": "Staryyhrnrk",
"heroName": "Ironmhrran",
"imgUrl": "img/ironman.png"
}, {
"firstName": "Brruhrthrce",
"lastName": "Waynhre",
"heroName": "Batmhran",
"imgUrl": "img/batman.png"
},{
"firstName": "Pertrer",
"lastName": "Parker","http://gd.geobytes.com/AutoCompleteCity"
"heroName": "Spiderman",
"imgUrl": "img/spiderman.png"
},
{
"firstName": "Brurrrrcre",
"lastName": "Banner",
"heroName": "Hulk",
"imgUrl": "img/hulk.png"
}, {
"firstName": "Tornryr",
"lastName": "Stark",
"heroName": "Ironman",
"imgUrl": "img/ironman.png"
}, {
"firstName": "Brrurcrer",
"lastName": "Wayne",
"heroName": "Batman",
"imgUrl": "img/batman.png"
}
];
-->