<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="it" lang="it">
<head>
    <?php echo $this->headMeta(); ?>
    <?php $auth=Zend_Auth::getInstance(); $this->headTitle()->append('Utente: '.$auth->getIdentity()->Nome." ".$auth->getIdentity()->Cognome); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/style.css'); ?>
    <?php echo $this->headScript() ?>
</head>

<body>
<div class="header-wrap">
    <div class="header">
        <div class="menu">
            <?= $this->render('_navuser.phtml')?>
        </div>
        <div class="social-media">
            <ul>
                <li><a href="#"><img src="<?=$this->baseUrl('images/aim.gif')?>" /></a></li>
                <li><a href="#"><img src="<?=$this->baseUrl('images/facebook.gif')?>" /></a></li>
                <li><a href="#"><img src="<?=$this->baseUrl('images/linkedin.gif')?>" /></a></li>
                <li><a href="#"><img src="<?=$this->baseUrl('images/twitter.gif')?>" /></a></li>
            </ul>
        </div>
    </div>
</div>
<!-- end of header wrapper -->
<div class="logo-sarch-wrap">
    <div class="logo-search-container">
        <div class="logo">
            <h1>PeopleBlog</h1>
        </div>

            <div class="search-input">
                <input id="searchbox" type="text" placeholder="Cerca Utenti..." />

            </div>

        </div>
    </div>
</div>
<!-- end of header wrapper -->
<?php /*<div class="banner-wrap marginBottom">
    <div class="banner-left"><img src="images/left-shadow.gif" /></div>
    <div class="banner">
        <div class="banner-image">
            <div class="banner-data">
                <div class="caption1">
                    <h1>Pellentesque et aliquet massa donec</h1>
                </div>
                <div class="caption2">
                    <h2> sit amet auctor anteroin sit amet elit doco ipory</h2>
                </div>
                <div class="caption3"> Fusce vel ipsum magna, nec tempor neque<br />
                    orem ipsum dolor sit ametris odonil kusi </div>
            </div>
        </div>
    </div>
    <div class="banner-right"><img src="images/right-shadow.gif" /></div>
</div>*/ ?>
<!-- end of header wrapper -->
<!-- end of panel wrapper -->
    <?php echo $this->layout()->content; ?>
    
    <!-- end of Sidebar -->
<!-- end of page wrapper -->
<div class="clearing"></div>
<div class="footer-wrapper marginTop">
    <div class="footer"> Copyright (c) Fsociety with the collaboration of Mr. Robot </div>
</div>

<script>
    var urlajax = '<?php echo $this->url(array('controller' => 'user', 'action' => 'updateajax',));?>';
    var urlaction ='<?php echo $this->url(array('controller' => 'user','action' =>'showuserprofile'));?>';
    var imagepath ='<?php echo $this->baseUrl("images/profiles/");?>';

</script>


</body>
</html>