<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="it" lang="it">
<head>
    <?php echo $this->headMeta(); ?>
    <?php $this->headTitle()->append('Amministratore'); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headScript() ?>

</head>
<body>
<div class="header-wrap">
    <div class="header">
        <div class="menu">
            <?= $this->render('_navadmin.phtml')?>
        </div>
        <div class="social-media">
            <ul>
                <li><a href="#"><img src="<?=$this->baseUrl('images/aim.gif')?>" /></a></li>
                <li><a href="#"><img src="<?=$this->baseUrl('images/facebook.gif')?>" /></a></li>
                <li><a href="#"><img src="<?=$this->baseUrl('images/linkedin.gif')?>" /></a></li>
                <li><a href="#"><img src="<?=$this->baseUrl('images/twitter.gif')?>" /></a></li>
            </ul>
        </div>
    </div>
</div>
<!-- end of header wrapper -->
<div class="logo-sarch-wrap">
    <div class="logo-search-container">
        <div class="logo">
            <h1>People Blog</h1>
        </div>
    </div>
</div>
<!-- end of header wrapper -->
<!-- end of header wrapper -->
<!-- end of panel wrapper -->
<div class="page-wrapper">
    <div class="primary-content">
        <p><?php echo $this->layout()->content; ?></p>
    </div>
    <!-- end of Primary content -->
    
    <!-- end of Sidebar -->
</div>
<!-- end of page wrapper -->
<div class="clearing"></div>
<div class="footer-wrapper marginTop">
    <div class="footer"> Copyright (c) Fsociety with the collaboration of Mr. Robot </div>
</div>

</body>
</html>