<div class="page-wrapper">


    <div class="primary-content">
        <div class="portfolio">
            <div class="title">

                <h1><?php echo $this->blogtitle;  ?> </h1>

                <h2>Puoi modificare qui le impostazioni della privacy di questo blog selezionando quali amici non possono vederlo</h2>


            </div>

            <div class="button-link">
                <div class="search-input">
                <input id="privacybox" type="text" placeholder="Cerca Utenti..." />
                </div>

            </div>


            <div id="results">
    <!--  CONTENUTO WRAPPATO -->





            </div>



        </div>



    </div>

</div>


<script>
    var iduser = '<?php echo $this->idprofile ?>';
    var idblog = '<?php echo $this->idblog ?>';
    var sonoio = '<?php echo $this->sonoio ?>';
    var staff = '<?php echo $this->staff ?>';

    var linkforupdateajax = '<?php echo $this->url(array('controller' => 'user', 'action' => 'updateajaxpost', 'idblog' => $this->idblog)); ?>';
    var linkmodif = '<?php echo $this->url(array('controller' => 'user', 'action' => 'modificapost', 'idpost' => '')); ?>';
    var linkdel = '<?php echo $this->url(array('controller' => 'user', 'action' => 'cancellapost', 'id_post' => '')); ?>';
    var linkforupdateajaxcomments = '<?php echo $this->url(array('controller' => 'user', 'action' => 'updateajaxcomment')); ?>';
    var linkimg = '<?php echo $this->baseUrl() . '/images/profiles/'?>';
    var linkdeletecomment = '<?php echo $this->url(array('controller' => 'user', 'action' => 'cancellacommento')); ?>';
    var linkcomment = '<?php echo $this->url(array('controller' => 'user', 'action' => 'commenta')); ?>';

    var urlAjaxSearchPrivacy = '<?php echo $this->url(array('controller' => 'user', 'action' => 'ajaxSearchForPrivacy')); ?>';
    var urlAjaxAddRule = '<?php echo $this->url(array('controller' => 'user', 'action' => 'privacyAddRule')); ?>';
    var urlajAjaxPrivacyReadAllRules = '<?php echo $this->url(array('controller' => 'user', 'action' => 'privacyReadRule')); ?>';
    var urlajAjaxPrivacyDeleteRule = '<?php echo $this->url(array('controller' => 'user', 'action' => 'privacyRemoveRule')); ?>';



</script>
<script src="<?php echo $this->baseUrl("js/privacyscript.js")?>"></script>
