<!-- notifiche -->
    <div class="primary-content">
        <p>
            <br><br><br>

            <br>
            Questo è il pannello utente. Seleziona l'azione da eseguire
            <?php if(!$this->messaggio=='') :?>
                <?php foreach ($this->messaggio as $mex) :?>
                    <?php echo $mex ?>
                    <?php $auth=Zend_Auth::getInstance()->getIdentity()->id; ?>
                <?php endforeach; ?>
                <a href="<?= $this->url(array(
                    'controller'=>'user',
                    'action'=>'gestisci',
                    'id'=>"$auth"),
                    'default',true);
                ?>"><?php echo $this->bottone; ?></a>
            <?php endif ?>

        </p>
    </div>
    <!-- sidebar -->
    <div class="sidebar marLeft30">
        <div class="panel">
            <div class="title">
                <h1><?php $nome=Zend_Auth::getInstance()->getIdentity()->Nome;
                    $cognome=Zend_Auth::getInstance()->getIdentity()->Cognome;
                    echo $nome.' '.$cognome.'<br><br>'.$eta=Zend_Auth::getInstance()->getIdentity()->eta.' anni'; ?></h1>
            </div>
            <div class="profilepic">
                <img src="<?php echo $this->baseUrl() . '/images/profiles/'.$immagine=Zend_Auth::getInstance()->getIdentity()->immagine; ?>" alt='Img' height="200" width="200"/>
            </div>
            <div class="content">
                <?php $interessi=Zend_Auth::getInstance()->getIdentity()->interessi;
                            echo $interessi; ?>
            </div>
            <div class="button-link"></div>
        </div>
        
    </div>