
    <div class="primary-content">
        <p>
            <br><br><br>

            <br>
            Questo è il pannello utente. Seleziona l'azione da eseguire<br><br>
            <?php if(!$this->messaggio=='') :?> 
            <?php foreach ($this->messaggio as $mex) :?>
            <?php echo $mex ?>
            <?php endforeach; ?>
            <?php endif ?>

        </p>
    </div>
    <!-- end of Primary content -->
    <div class="sidebar marLeft30">
        <div class="panel">
            <div class="title">
                <h1><?php $nome=Zend_Auth::getInstance()->getIdentity()->Nome;
                    $cognome=Zend_Auth::getInstance()->getIdentity()->Cognome;
                    echo $nome.' '.$cognome.' '; ?></h1>
            </div>
            <div class="content">
                <ul>
                    <li>Bla</li>
                    <li>Bla</li>
                </ul>
            </div>
            <div class="button-link"></div>
        </div>
        
    </div>