

<div class="primary-content">
        <p>
            <br><br><br>

            <br>
Questo è il pannello utente gigi. Seleziona l'azione da eseguire


        </p>
    </div>

    <div class="sidebar marLeft30">
        <div class="panel">
            <div class="title">
                <h1><?php echo $this->nome.' '.$this->cognome;  ?> </h1>
            </div>
            <div class="content">
                <ul>
                    <?php
                    echo $this->amici;
                    if($this->sonoio == false)
                    {
                        if($this->amici)
                        {
                            echo '<li><a href="';
                            echo $this->url(array('controller'=>'user',
                                'action'=>'rimuoviamico',
                                'id'=>$this->idprofile),
                                'default',true);
                            echo'"title="Rimuovi">-Rimuovi</a>
    </li>';

                        }else{
                            echo '<li><a href="';
                            echo $this->url(array('controller'=>'user',
                                'action'=>'aggiungiamico',
                                'id'=>$this->idprofile),
                                'default',true);
                            echo'"title="Aggiungi">+Aggiungi</a>
    </li>';
                           } } ?>
                    <li><p>età:<?php echo $this->eta;  ?> anni</p></li>
                    <li><p><?php echo $this->interessi;  ?></p></li>



                </ul>
            </div>
            <div class="button-link"></div>
        </div>
        
    </div>