<div class="page-wrapper">


<div class="primary-content">
    <div class="portfolio">
        <div class="title" id="results">

            <h1>BLOG DI <?php echo $this->nome.' '.$this->cognome;  ?> </h1> </h1>
            <?php
            if($this->sonoio == true)
            { echo'<div class="button-link"><a href="#">+ CREA BLOG</a></div>
        </div>'; }
            ?>


            

    </div>


    </div>
</div>

    <div class="sidebar marLeft30">
        <div class="panel">
            <div class="profilepic">
                <img src="<?php echo $this->baseUrl() . '/images/profiles/'.$this->immagine; ?>" alt='Img' height="200" width="200"/>
            </div>
            <div class="title">
                <h1><?php echo $this->nome.' '.$this->cognome;  ?> </h1>
            </div>
            <div class="content">
                <ul>
                    <?php
                    if($this->sonoio == false)
                    {
                        if($this->amici)
                        {
                            echo '<li><a href="';
                            echo $this->url(array('controller'=>'user',
                                'action'=>'rimuoviamico',
                                'id'=>$this->idprofile),
                                'default',true);
                            echo'"title="Rimuovi">-Rimuovi</a>
    </li>';

                        }else{
                            echo '<li><a href="';
                            echo $this->url(array('controller'=>'user',
                                'action'=>'aggiungiamico',
                                'id'=>$this->idprofile),
                                'default',true);
                            echo'"title="Aggiungi">+Aggiungi</a>
    </li>';
                           } } ?>
                    <li><p>età:<?php echo $this->eta;  ?> anni</p></li>
                    <li><p><?php echo $this->interessi;  ?></p></li>
                    


                </ul>
            </div>
            <div class="button-link"></div>
        </div>
        
    </div>

    <id="results"><!-- results appear here --></ul>

    <div class="loading-info"><img src="ajax-loader.gif" /></div>
<script>
    var link = '<?php echo $this->url(array('controller' => 'user', 'action' => 'updateajaxblog', 'id' => $this->idprofile)); ?>';
</script>
    <script src="<?php echo $this->baseUrl("js/blogscript.js")?>"></script>
