<div class="primary-content">
    <p>Utilizza questa tabella per modificare le informazioni utente nel database</p><br><br><br>
    <div class="datagrid">

<table class="thead">
    <tr>
        <th>Id</th>
        <th>Nome</th>
        <th>Cognome</th>
        <th>Email</th>
        <th>Password</th>
        <th>Ruolo</th>
        <th>Modifica</th>
        <th>Cancella</th>
        <th>Amici</th>
    </tr>
    <?php foreach($this->risultato as $utenti) :?>

        <?php $id=$utenti['id']; ?>
        <?php echo "<tr>
          <td>" . $utenti['id'] . "</td>
          <td>" . $utenti['Nome'] . "</td>
          <td>" . $utenti['Cognome'] . "</td>
          <td>" . $utenti['email'] . "</td>
          <td>" . $utenti['password'] . "</td>
          <td>" . $utenti['ruolo'] . "</td>
          <td>"; ?><a href="<?= $this->url(array(
            'controller'=>'admin',
            'action'=>'modificautente',
            'id'=>"$id"),
            'default',true);
        ?>"><?php echo $this->bottonemod ?></a>
        <?php echo"</td>
        <td>"; ?><a href="<?= $this->url(array(
            'controller'=>'admin',
            'action'=>'cancellautente',
            'id'=>"$id"),
            'default',true);
        ?>"><?php echo $this->bottonedel ?></a>
        <?php echo"</td>
        <td>"; ?><a href="<?= $this->url(array(
            'controller'=>'admin',
            'action'=>'visualizzaamici',
            'id'=>"$id"),
            'default',true);
        ?>"><?php echo $this->bottoneamici ?></a>
        <?php echo"</td>
        <td>"; ?><a href="<?= $this->url(array(
            'controller'=>'admin',
            'action'=>'visualizzarichieste',
            'id'=>"$id"),
            'default',true);
        ?>"><?php echo $this->bottonerichieste ?></a>
        <?php echo"</td>
        </tr>"; ?>

    <?php endforeach ?>
</table>
</div></div>