<?php foreach($this->posts as $posts) :?>
    <?php $a=$posts['datetime']; ?>
<div class="panel">
    <div class="title">
        <h1><?php echo $posts['titolo'] ?></h1>
        <?php $_auth=Zend_Auth::getInstance();
        $cognome=$_auth->getIdentity()->Cognome;
        $nome=$_auth->getIdentity()->Nome; ?>
        <?php if(($nome==$posts['Nome'])&&($cognome==$posts['Cognome'])) :?>
        <table><tr><th><a href="<?= $this->url(array(
                        'controller'=>'blog',
                        'action'=>'modificapost',
                        'a'=>"$a"),
                        'default',true);
                    ?>"><?php echo $this->bottonemod ?></a></th><th><a href="<?= $this->url(array(
                        'controller'=>'blog',
                        'action'=>'cancellapost',
                        'a'=>"$a"),
                        'default',true);
                    ?>"><?php echo $this->bottonedel ?></a></th></tr></table>
        <?php endif; ?>
    </div>
    <div class="content padBottom"> <!--<img src="images/executive.gif" /> -->
        <p><?php echo $posts['post'] ?></p>
    </div>
    <div class="clearing"></div>
    <div class="title padTop">
        <h1 class="padTop">Inviato da <?php echo $posts['Nome'].' '.$posts['Cognome'].' il '.$posts['datetime'].' '?></h1>
    </div>
    <div class="button-link"></div>
    <div class="button-link"><a href="#">| - Commenta - |</a> </div><br><br>
    <div class="comment-wrapper">
        <h3 class="comment-title">Commenti lasciati:</h3>
        <div class="comment-insert">
            <h3 class="chi">Di qualcosa...</h3>
            <div class="comment-insert-container">
                <textarea id="comment-post-text" class="comment-insert-text"></textarea>
            </div>
            <div class="post-button-wrapper" id="invia-btn">
                Invia
            </div>

        </div>
        <div class="comments-list">
            <ul class="comments-holder">
                <li class="comment-holder" id="1">
                    <div class="user-img"><img src="images/img2.jpg" class="user-imgpic"/></div>
                    <div class="comment-body">
                        <h3 class="username-field">
                            Bla
                        </h3>
                        <div class="comment-text">
                            Il testo qui Il testo qui Il testo qui Il testo qui Il testo qui Il testo qui Il testo qui Il testo qui
                            Il testo qui Il testo qui Il testo qui Il testo qui Il testo qui Il testo qui Il testo qui Il testo qui
                            Il testo qui Il testo qui Il testo qui Il testo qui Il testo qui Il testo qui Il testo qui Il testo qui
                            Il testo qui Il testo qui Il testo qui Il testo qui Il testo qui Il testo qui Il testo qui Il testo qui Il testo qui
                        </div>
                    </div>
                    <div class="comment-buttons-holder">
                        <ul>
                            <li class="delete-button">
                                X
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="comment-holder" id="1">
                    <div class="user-img"><img src="images/img2.jpg" class="user-imgpic"/></div>
                    <div class="comment-body">
                        <h3 class="username-field">
                            Bla
                        </h3>
                        <div class="comment-text">
                            Il testo qui
                        </div>
                    </div>
                    <div class="comment-buttons-holder">
                        <ul>
                            <li class="delete-button">
                                X
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>
<?php endforeach ?>